import { Product } from './types';

export const COLORS = {
  blush: 'linear-gradient(145deg, #f5d5c8, #e8b0a0)',
  sage: 'linear-gradient(135deg, #d8e8d0, #c0d8b8)',
  lavender: 'linear-gradient(155deg, #d0d4f0, #b8bce8)',
  peach: 'linear-gradient(125deg, #f5e8d0, #e8d0a8)',
  mint: 'linear-gradient(135deg, #d0f0ec, #a8dcd8)',
  lilac: 'linear-gradient(125deg, #e8d0f8, #d0b0f0)',
  ivory: 'linear-gradient(145deg, #f0e8d0, #e0d0a8)',
  butter: 'linear-gradient(155deg, #f8e8c8, #f0d0a0)',
};

export const CATEGORIES = {
  kurta: 'Kurta',
  coord: 'Co-ord Set',
  dress: 'Dress',
  suit: 'Suit Set',
  sharara: 'Sharara',
};

export const DEFAULT_PRODUCTS: Product[] = [
  // === KURTAS (10) ===
  {
    id: 1,
    name: 'Sage Linen Kurta',
    desc: 'Breathable linen kurta with delicate hand-block printed floral vines',
    price: 1199,
    oldPrice: 1599,
    category: 'kurta',
    emoji: '🌿',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    color: 'sage',
    badge: 'Trending',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=600&q=80'],
  },
  {
    id: 2,
    name: 'Emerald Silk Kurta',
    desc: 'Royal emerald green handwoven Banarasi silk kurta with golden zari borders',
    price: 2499,
    oldPrice: 3299,
    category: 'kurta',
    emoji: '💚',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'mint',
    badge: 'Luxury',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80'],
  },
  {
    id: 3,
    name: 'Ivory Chikankari Kurta',
    desc: 'Authentic Lucknowi chikankari embroidery on soft, airy premium ivory cotton',
    price: 1899,
    oldPrice: 2399,
    category: 'kurta',
    emoji: '✨',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    color: 'ivory',
    badge: 'Best Seller',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80'],
  },
  {
    id: 4,
    name: 'Mustard Meadow Kurta',
    desc: 'Rich mustard yellow kurta with intricate hand-block floral motifs on premium linen',
    price: 1099,
    oldPrice: 1499,
    category: 'kurta',
    emoji: '🌻',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'butter',
    badge: 'Festive',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80'],
  },
  {
    id: 5,
    name: 'Rosewood A-Line Kurta',
    desc: 'Deep rosewood red A-line kurta featuring hand-painted botanical artwork on the yoke',
    price: 1399,
    oldPrice: 1799,
    category: 'kurta',
    emoji: '🌹',
    sizes: ['XS', 'S', 'M', 'L'],
    color: 'blush',
    badge: 'Exclusive',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80'],
  },
  {
    id: 6,
    name: 'Teal Breeze Kurta',
    desc: 'Breathable asymmetrical teal cotton kurta with geometric block prints and lace trims',
    price: 999,
    oldPrice: 1299,
    category: 'kurta',
    emoji: '👗',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'mint',
    badge: '',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=600&q=80'],
  },
  {
    id: 7,
    name: 'Marigold Festive Kurta',
    desc: 'Radiantly bright saffron orange cotton-silk blend kurta with delicate gotapatti lace',
    price: 1799,
    oldPrice: null,
    category: 'kurta',
    emoji: '🍊',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'peach',
    badge: 'New',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80'],
  },
  {
    id: 8,
    name: 'Indigo Dabu Kurta',
    desc: 'Traditional hand-dyed Jaipur dabu-print indigo regular fit cotton kurta with pockets',
    price: 1299,
    oldPrice: 1699,
    category: 'kurta',
    emoji: '🌀',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    color: 'lavender',
    badge: 'Traditional',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80'],
  },
  {
    id: 9,
    name: 'Crimson Khadi Kurta',
    desc: 'Rich crimson red handspun khadi kurta featuring elegant wooden buttons and fold-up sleeves',
    price: 1549,
    oldPrice: 1999,
    category: 'kurta',
    emoji: '🍷',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'blush',
    badge: 'Organic',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=80'],
  },
  {
    id: 10,
    name: 'Amethyst Flared Kurta',
    desc: 'Flowy amethyst purple umbrella kurta with premium scalloped silver borders',
    price: 1699,
    oldPrice: 2199,
    category: 'kurta',
    emoji: '🪻',
    sizes: ['S', 'M', 'L'],
    color: 'lilac',
    badge: 'Limited',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&q=80'],
  },

  // === CO-ORD SETS (10) ===
  {
    id: 11,
    name: 'Blush Satin Co-ord',
    desc: 'Liquid luxury blush pink satin button-down shirt paired with flared satin trousers',
    price: 2299,
    oldPrice: 2999,
    category: 'coord',
    emoji: '🌸',
    sizes: ['S', 'M', 'L'],
    color: 'blush',
    badge: 'Premium',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80'],
  },
  {
    id: 12,
    name: 'Sage Chevron Co-ord',
    desc: 'Sage green geometric chevron print top and wide-leg trousers in airy modal fabric',
    price: 1799,
    oldPrice: 2299,
    category: 'coord',
    emoji: '🎋',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    color: 'sage',
    badge: 'New',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80'],
  },
  {
    id: 13,
    name: 'Lilac Garden Co-ord',
    desc: 'Premium lilac floral-printed tunic with matching culottes in breathable cotton-linen',
    price: 1999,
    oldPrice: 2599,
    category: 'coord',
    emoji: '💐',
    sizes: ['S', 'M', 'L'],
    color: 'lilac',
    badge: 'Best Seller',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&q=80'],
  },
  {
    id: 14,
    name: 'Peach Sunset Co-ord',
    desc: 'Dual-toned peach ombre pleated top and trousers for an effortlessly chic evening look',
    price: 2199,
    oldPrice: 2899,
    category: 'coord',
    emoji: '🍑',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'peach',
    badge: 'Stylist Choice',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80'],
  },
  {
    id: 15,
    name: 'Midnight Bloom Co-ord',
    desc: 'Deep indigo blue matching wrap-around kimono top and parallel pants with gold foil prints',
    price: 1899,
    oldPrice: 2499,
    category: 'coord',
    emoji: '🎆',
    sizes: ['XS', 'S', 'M', 'L'],
    color: 'lavender',
    badge: 'Exclusive',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80'],
  },
  {
    id: 16,
    name: 'Oatmeal Minimal Co-ord',
    desc: 'Clean oatmeal ivory collar neck top with high-waisted cigarette pants in pure khadi',
    price: 1699,
    oldPrice: null,
    category: 'coord',
    emoji: '🌾',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'ivory',
    badge: 'Minimalist',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&q=80'],
  },
  {
    id: 17,
    name: 'Mint Meadow Co-ord',
    desc: 'Pastel mint linen vest and relaxed-fit tailored trousers for crisp afternoon elegance',
    price: 1849,
    oldPrice: 2399,
    category: 'coord',
    emoji: '🍃',
    sizes: ['XS', 'S', 'M', 'L'],
    color: 'mint',
    badge: 'Pure Linen',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1554412933-514a83d2f3c8?w=600&q=80'],
  },
  {
    id: 18,
    name: 'Tangerine Pleated Co-ord',
    desc: 'Bright tangerine orange modern pleated tunic with matching slim designer trousers',
    price: 2399,
    oldPrice: 3099,
    category: 'coord',
    emoji: '🍊',
    sizes: ['S', 'M', 'L'],
    color: 'butter',
    badge: 'Stylist Pick',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=600&q=80'],
  },
  {
    id: 19,
    name: 'Olive Draped Co-ord',
    desc: 'Olive green asymmetrical draped fusion high-low top and palazzo pants in soft georgette',
    price: 2599,
    oldPrice: 3299,
    category: 'coord',
    emoji: '🥑',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'sage',
    badge: 'Modish',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?w=600&q=80'],
  },
  {
    id: 20,
    name: 'Ruby Silk Co-ord',
    desc: 'Glossy ruby red premium mulberry silk short kurta and matching comfort-fit trousers',
    price: 2999,
    oldPrice: 3999,
    category: 'coord',
    emoji: '🍷',
    sizes: ['S', 'M', 'L'],
    color: 'blush',
    badge: 'Royal',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80'],
  },

  // === DRESSES (10) ===
  {
    id: 21,
    name: 'Buttercup Tiered Midi',
    desc: 'Flowing buttercup yellow tiered maxi dress with dainty hand-embroidered shoulder straps',
    price: 1499,
    oldPrice: 1999,
    category: 'dress',
    emoji: '🌼',
    sizes: ['XS', 'S', 'M', 'L'],
    color: 'butter',
    badge: 'Charming',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1621784563330-caee0b138a00?w=600&q=80'],
  },
  {
    id: 22,
    name: 'Blush Rose Slit Maxi',
    desc: 'Ethereal blush pink georgette halter-neck dress with an elegant side slits configuration',
    price: 1899,
    oldPrice: 2499,
    category: 'dress',
    emoji: '🌹',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'blush',
    badge: 'Romantic',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&q=80'],
  },
  {
    id: 23,
    name: 'Sage Meadow Wrap Dress',
    desc: 'Handprinted organic linen wrap dress in muted sage green with adjustable sash-belt',
    price: 1299,
    oldPrice: 1699,
    category: 'dress',
    emoji: '🌿',
    sizes: ['S', 'M', 'L'],
    color: 'sage',
    badge: 'New Arrival',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=600&q=80'],
  },
  {
    id: 24,
    name: 'Lavish Lavender Slit Midi',
    desc: 'Romantic pastel lilac-lavender midi dress with custom scalloped neckline and puff sleeves',
    price: 1599,
    oldPrice: null,
    category: 'dress',
    emoji: '💜',
    sizes: ['XS', 'S', 'M', 'L'],
    color: 'lavender',
    badge: 'Popular',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80'],
  },
  {
    id: 25,
    name: 'Mint Serenade Halter',
    desc: 'Vibrant mint-blue tiered halter linen dress, perfect for warm afternoon events',
    price: 1699,
    oldPrice: 2199,
    category: 'dress',
    emoji: '🍹',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'mint',
    badge: 'Vacay Vibes',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&q=80'],
  },
  {
    id: 26,
    name: 'Peach Sorbet Flare Dress',
    desc: 'Flouncy fit-and-flare cotton dress featuring intricate eyelet lace stitching',
    price: 1399,
    oldPrice: 1899,
    category: 'dress',
    emoji: '🍑',
    sizes: ['S', 'M', 'L'],
    color: 'peach',
    badge: 'Sweet Pastel',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1605497746445-97d1b0a9ebd2?w=600&q=80'],
  },
  {
    id: 27,
    name: 'Ivory Sun-Kissed Dress',
    desc: 'Off-shoulder Ivory cotton linen sundress adorned with delicate lace hems',
    price: 1799,
    oldPrice: 2299,
    category: 'dress',
    emoji: '☀️',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    color: 'ivory',
    badge: 'Breezy',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80'],
  },
  {
    id: 28,
    name: 'Lilac Ribbon Midi',
    desc: 'Retro tiered dress in soft lilac cotton with adjustable waist ribbon-tie detailing',
    price: 1449,
    oldPrice: 1899,
    category: 'dress',
    emoji: '🎀',
    sizes: ['S', 'M', 'L'],
    color: 'lilac',
    badge: 'Sweetheart',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1534126416832-a88fdf2911c2?w=600&q=80'],
  },
  {
    id: 29,
    name: 'Emerald Pleated Dress',
    desc: 'Luxury green pleated georgette maxi dress featuring a statement collar and billowy sleeves',
    price: 2799,
    oldPrice: 3499,
    category: 'dress',
    emoji: '🟢',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'mint',
    badge: 'High Fashion',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80'],
  },
  {
    id: 30,
    name: 'Butter Cream Slip Dress',
    desc: 'Effortless butter-yellow cowl-neck slip dress in premium heavy-weight viscose satin',
    price: 1999,
    oldPrice: 2699,
    category: 'dress',
    emoji: '🕯️',
    sizes: ['S', 'M', 'L'],
    color: 'butter',
    badge: 'Luxe Satin',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80'],
  },

  // === SUIT SETS (10) ===
  {
    id: 31,
    name: 'Lavender Opulence Suit',
    desc: 'Majestic 3-piece heavy-embroidered georgette Anarkali suit set with shining organza dupatta',
    price: 3499,
    oldPrice: 4499,
    category: 'suit',
    emoji: '🧚',
    sizes: ['S', 'M', 'L'],
    color: 'lavender',
    badge: 'Regal Heritage',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=80'],
  },
  {
    id: 32,
    name: 'Rose Gold Silk Suit',
    desc: 'Rich rose gold raw silk straight kameez with tailored trousers and a cascading tissue dupatta',
    price: 4299,
    oldPrice: 5499,
    category: 'suit',
    emoji: '🔱',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'blush',
    badge: 'Festive Wardrobe',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&q=80'],
  },
  {
    id: 33,
    name: 'Ivory Monarch Suit Set',
    desc: 'Royal ivory cotton-silk Chanderi straight suit featuring heirloom hand-done mirror highlights',
    price: 3899,
    oldPrice: null,
    category: 'suit',
    emoji: '👑',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'ivory',
    badge: 'Heirloom',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&q=80'],
  },
  {
    id: 34,
    name: 'Mint Glaze Silk Suit',
    desc: 'Pure Banarasi mint silk straight suit set accompanied by heavy woven brocade dupatta',
    price: 4499,
    oldPrice: 5999,
    category: 'suit',
    emoji: '❇️',
    sizes: ['S', 'M', 'L'],
    color: 'mint',
    badge: 'Royal Handwoven',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=600&q=80'],
  },
  {
    id: 35,
    name: 'Peach Blossom Suit Set',
    desc: 'Sophisticated heavy georgette suit adorned with intricate pastel floral threadwork',
    price: 2999,
    oldPrice: 3799,
    category: 'suit',
    emoji: '🌸',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'peach',
    badge: 'Wedding Guest',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1479936343636-73dad5a8ff37?w=600&q=80'],
  },
  {
    id: 36,
    name: 'Sage Regal Chanderi Suit',
    desc: 'Pristine mint-sage green Chanderi silk suit decorated with unique hand-block dabu patterns',
    price: 3299,
    oldPrice: 3999,
    category: 'suit',
    emoji: '🏹',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    color: 'sage',
    badge: 'Signature',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&q=80'],
  },
  {
    id: 37,
    name: 'Marigold Gota Suit',
    desc: 'Brilliant saffron yellow festive cotton suit with heavy golden gotapatti embellishments',
    price: 2799,
    oldPrice: 3499,
    category: 'suit',
    emoji: '🌟',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'butter',
    badge: 'Festive Glow',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=600&q=80'],
  },
  {
    id: 38,
    name: 'Lilac Dusk Salwar Set',
    desc: 'Traditional Punjabi style lilac salwar-kameez set with heavily woven phulkari dupatta',
    price: 2499,
    oldPrice: 3199,
    category: 'suit',
    emoji: '🍇',
    sizes: ['S', 'M', 'L'],
    color: 'lilac',
    badge: 'Heritage Classic',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1551803091-e006598bc365?w=600&q=80'],
  },
  {
    id: 39,
    name: 'Midnight Indigo Suit Set',
    desc: 'Deep starry-night indigo blue straight cut suit highlighting subtle silver sequence detailing',
    price: 3199,
    oldPrice: 3999,
    category: 'suit',
    emoji: '🌌',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'lavender',
    badge: 'Celestial',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1548142813-c348350df52b?w=600&q=80'],
  },
  {
    id: 40,
    name: 'Crimson Rose Silk Suit',
    desc: 'Extravagant deep-red heritage Banarasi handloom silk suit with heavy golden zari panels',
    price: 4999,
    oldPrice: 6499,
    category: 'suit',
    emoji: '🍁',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'blush',
    badge: 'Luxury Bridal',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80'],
  },

  // === SHARARAS (10) ===
  {
    id: 41,
    name: 'Lilac Enchantment Sharara',
    desc: 'Flowy lilac chiffon heavily flared sharara paired with raw silk short peplum and net dupatta',
    price: 3299,
    oldPrice: 4299,
    category: 'sharara',
    emoji: '🪻',
    sizes: ['S', 'M', 'L'],
    color: 'lilac',
    badge: 'Bestseller',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80'],
  },
  {
    id: 42,
    name: 'Sage Harmony Cotton Sharara',
    desc: 'Lightweight minty sage green tiered cotton sharara with hand-blocked gold foil floral motifs',
    price: 2199,
    oldPrice: 2899,
    category: 'sharara',
    emoji: '🍃',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    color: 'sage',
    badge: 'Artisanal',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80'],
  },
  {
    id: 43,
    name: 'Blush Petals Sharara Set',
    desc: 'Romantic baby-pink georgette short kurta and extra wide flared sharara decorated with pearls',
    price: 3499,
    oldPrice: null,
    category: 'sharara',
    emoji: '🌷',
    sizes: ['S', 'M', 'L'],
    color: 'blush',
    badge: 'New Trend',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80'],
  },
  {
    id: 44,
    name: 'Ivory Royal Silk Sharara',
    desc: 'Luxurious heavy crepe ivory sharara set showcasing authentic Lucknowi chikankari work',
    price: 4199,
    oldPrice: 5299,
    category: 'sharara',
    emoji: '🕌',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'ivory',
    badge: 'Classic Ivory',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&q=80'],
  },
  {
    id: 45,
    name: 'Mint Blossom Tiered Sharara',
    desc: 'Pastel mint-green chiffon tiered sharara set containing fine silver-trimmed edges',
    price: 2599,
    oldPrice: 3299,
    category: 'sharara',
    emoji: '💎',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'mint',
    badge: 'Vibrant Pastel',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=600&q=80'],
  },
  {
    id: 46,
    name: 'Peach Sunrise Satin Sharara',
    desc: 'Glamorous sunset peach satin short kurti and matching double-layered voluminous sharara pants',
    price: 2899,
    oldPrice: 3699,
    category: 'sharara',
    emoji: '🌅',
    sizes: ['XS', 'S', 'M', 'L'],
    color: 'peach',
    badge: 'Festive Satin',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=600&q=80'],
  },
  {
    id: 47,
    name: 'Tangerine Festive Sharara',
    desc: 'Bright tangerine orange georgette short tunic and tiered matching sharara with mirror details',
    price: 2699,
    oldPrice: 3399,
    category: 'sharara',
    emoji: '☀️',
    sizes: ['S', 'M', 'L'],
    color: 'butter',
    badge: 'Vibrant Saffron',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1490139738914-3a92b21b04a4?w=600&q=80'],
  },
  {
    id: 48,
    name: 'Buttercup Sunbeam Sharara',
    desc: 'Cheerful yellow flared pure cotton sharara set with simple mirror-embroidered short sleeves kurta',
    price: 1999,
    oldPrice: 2499,
    category: 'sharara',
    emoji: '✨',
    sizes: ['S', 'M', 'L'],
    color: 'butter',
    badge: 'Comfort Wear',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80'],
  },
  {
    id: 49,
    name: 'Lavish Indigo Velvet Sharara',
    desc: 'Regal deep sapphire blue velvet short kurti and matching velvet sharara with gold lace borders',
    price: 4399,
    oldPrice: 5499,
    category: 'sharara',
    emoji: '🔮',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'lavender',
    badge: 'Velvet Silk',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=600&q=80'],
  },
  {
    id: 50,
    name: 'Royal Ruby Silk Sharara Set',
    desc: 'Crimson ruby red heritage art-silk heavily flared sharara paired with handworked zari peplum',
    price: 4799,
    oldPrice: 5999,
    category: 'sharara',
    emoji: '💎',
    sizes: ['S', 'M', 'L'],
    color: 'blush',
    badge: 'Exclusive Bridal',
    oos: false,
    imgs: ['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80'],
  }
];
